import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [phoneNumber, setPhoneNumber] = useState("");
  const [message, setMessage] = useState("");

  const sendMessage = async () => {
    try {
      const result = await (
        await fetch("/api/send-by-vonage", {
          body: JSON.stringify({ phoneNumber, message }),
          headers: { "Content-Type": "application/json" },
          method: "POST",
        })
      ).json();
      console.log(result);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next Full Stack SMS Sender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next SMS Sender</a>
        </h1>

        <p className={styles.description}>
          Get started by entering phone number
        </p>
        <input
          type="tel"
          placeholder="Enter phone number"
          value={phoneNumber}
          onChange={(e) => setPhoneNumber(e.target.value)}
          className="border border-blue-100 rounded p-2 w-full max-w-sm my-2"
        />
        <textarea
          placeholder="Enter message"
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          className="border border-blue-100 rounded p-2 w-full max-w-sm my-2"
        ></textarea>
        <button
          onClick={sendMessage}
          className="border border-blue-100 rounded p-2 w-full max-w-sm my-2 text-blue-600 hover:bg-blue-600 hover:text-white"
        >
          Send Message
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
